services:
  identity.db:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${IDENTITY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${IDENTITY_POSTGRES_PASSWORD}
      POSTGRES_DB: ${IDENTITY_POSTGRES_DB}
      POSTGRES_PORT: ${IDENTITY_POSTGRES_PORT}
    ports:
      - '${IDENTITY_POSTGRES_PORT:-5431}:5432'
    volumes:
      - identity.dev.data:/var/lib/postgresql/data

volumes:
  identity.dev.data: